matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libwxgtk3.0-dev libchm-dev
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" 

    # works on Trusty
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7.0
          packages:
            - clang-7.0 libwxgtk3.0-dev libchm-dev
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

language: c++

before_install:
  - eval "${MATRIX_EVAL}"

script:
    ./bootstrap && ./configure && make
