matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libwxgtk3.0-dev libchm-dev
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" 

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
              # - llvm-toolchain-xenial-7.0
          packages:
            - libwxgtk3.0-dev libchm-dev
      compiler: clang

    - os: osx 
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - gettext
            - wxmac

language: c++

before_install:
  - eval "${MATRIX_EVAL}"

script:
    ./bootstrap && ./configure && make
