matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libwxgtk3.0-dev libchm-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" 

language: c++
compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
    ./bootstrap && ./configure && make
