matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"

    - os: osx
      osx_image: xcode10.1

language: c++

compiler: gcc

os:
  - linux
  - osx

before_install:
  - sudo apt-get install -y libwxgtk3.0-dev libchm-dev

script:
    ./bootstrap && ./configure && make
